select*from customer limit 20

--what is total revenue generated by male vs female customers

select  gender,SUM(purchase_amount) as revenue from customer group by gender

---#which customer uses the discount but still spent mmmorethan average purchase amout
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--which are the top 5 with the highest average review rating
select item_purchased,Round(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc


---compare the standard purchase amount in express shipping
select shipping_type,
AVG(purchase_amount)
from customer
where shipping_type in('Standard','Express')
group by Shipping_type

---Do subscribe customer spend more?Compare the average spend and total revenue
--between subscriber and non subscriber
select subscription_status,count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc


--which 5 prodducts have the highest package of percentage with the discount apllied
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied='Yes' Then 1 ELSE 0 END)/Count(*),2) as discount_rate from customer
group by item_purchased
order by discount_rate desc
limit 5

--segment customer are into NEW Returning and lOYAL based on thier total
--number of tthhe previous purchases and show the count of each segment


--what arethe top 3 most purchasd products
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)Desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank, category,item_purchased,total_orders from item_counts
where item_rank<3

---are the customer who are repeat buyers also likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status


---what is the revenue contribution of each age group
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc






